name: xclim
channels:
  - conda-forge
dependencies:
  - python >=3.11,<3.14
  - boltons >=20.1
  - bottleneck >=1.3.1
  - cf_xarray >=0.9.3
  - cftime >=1.4.1
  - click >=8.1
  - dask >=2024.8.1
  - filelock >=3.14.0
  - numba >=0.57.0
  - numpy >=1.25.0
  - packaging >=24.0
  - pandas >=2.2.0
  - pint >=0.24.4
  - pyarrow >=15.0.0  # Strongly encouraged for Pandas v2.2.0+
  - pyyaml >=6.0.1
  - scikit-learn >=1.2.0
  - scipy >=1.11.0
  - xarray >=2023.11.0,!=2024.10.0
  - yamale >=5.0.0
  # Extras
  - flox >=0.9
  - xsdba >=0.4.0
  - numbagg >= 0.8
  # lmoments3 - Not an official dependency but required for some Jupyter notebooks
  - lmoments3 >=1.0.7
  # Testing and development dependencies
  - bump-my-version >=1.2.3
  - cairosvg >=2.6.0
  - codespell >=2.4.1
  - coverage >=7.5.0
  - deptry >=0.23.0
  - distributed >=2.0
  - flake8 >=7.3.0
  - flake8-rst-docstrings >=0.4.0
  - flit >=3.11.0,<4.0
  - furo >=2023.9.10
  - h5netcdf >=1.5.0
  - h5py >=3.12.1
  - ipykernel
  - ipython >=8.10.0
  - matplotlib >=3.7.0
  - mypy >=1.14.1
  - nbconvert >=7.16.4
  - nbsphinx >=0.9.5
  - nbval >=0.11.0
  - nc-time-axis >=1.4.1
  - netcdf4 <1.7.3   # Required for some Jupyter notebooks
  - notebook
  - numpydoc >=1.9.0
  - pandas-stubs >=2.2
  - pip >=25.0
  - pooch >=1.8.0
  - pre-commit >=3.7
  - pybtex >=0.24.0
  - pylint >=3.3.1
  - pytest >=9.0.0
  - pytest-cov >=5.0.0
  - pytest-socket >=0.6.0
  - pytest-timeout >=2.4.0
  - pytest-xdist >=3.2
  - ruff >=0.13.3
  - sphinx >=8.2.0
  - sphinx-autobuild >=2024.4.16
  - sphinx-autodoc-typehints >=3.1.0
  - sphinx-codeautolink >=0.16.2
  - sphinx-copybutton
  - sphinx-mdinclude
  - sphinxcontrib-bibtex
  - sphinxcontrib-svg2pdfconverter
  - tokenize-rt >=5.2.0
  - tox >=4.31.0
  - tox-gh >=1.5.0
  - vulture =2.14
  - xdoctest >=1.2.0 # v1.3.0 not yet available on conda-forge
  - yamllint >=1.35.1
  # Temporary Fixes
  - importlib-metadata <8.7.0  # Issues with dask >=2025.5.1 on Python3.11
