name: xclim
channels:
 - conda-forge
 - defaults
dependencies:
 - numpy>=1.16
 - xarray>=0.17
 - scipy>=1.2
 - numba
 - pandas>=0.23
 - cftime>=1.4.1
 - poppler>=0.67
 - dask>=2.6.0
 - bottleneck>=1.3.1,<1.4
 - pint>=0.9
 - boltons>=20.1
 - scikit-learn>=0.21.3
 - Click
 - netCDF4>=1.4
 - clisops>=0.4.0
 - pyyaml
 - jsonpickle
