name: xclim
channels:
    - conda-forge
    - defaults
dependencies:
    - numpy>=1.16
    - xarray>=0.17
    - cf_xarray>=0.6.1
    - scipy>=1.2
    - numba
    - pandas>=0.23
    - cftime>=1.4.1
    - poppler>=0.67
    - dask>=2.6.0
    - bottleneck>=1.3.1,<1.4
    - pint>=0.9
    - boltons>=20.1
    - scikit-learn>=0.21.3
    - Click
    - pyyaml
    - jsonpickle
    # Testing and development dependencies
    - black
    - bump2version
    - coverage
    - distributed>=2.0
    - flake8
    - ipykernel
    - matplotlib
    - mypy
    - nbval
    - nc-time-axis
    - netCDF4>=1.4
    - pooch
    - pre_commit
    - pydocstyle
    - pylint
    - pytest
    - pytest-cov
    - pytest-runner
    - sphinx
    - sphinx_rtd_theme
    - statsmodels
    - tokenize-rt
    - tox
    - xdoctest
    - yamale
    - yamllint
