name: xclim
channels:
 - conda-forge
 - defaults
dependencies:
 - numpy>=1.16
 - xarray>=0.14.1
 - scipy>=1.2
 - pandas>=0.23
 - cftime
 - netCDF4
 - dask>=2.8.0
 - bottleneck>=1.3.1
 - pyproj
 - pint>=0.9
 - boltons>=19.2
 - scikit-learn>=0.21.3
 - Click
