name: xclim
channels:
    - conda-forge
    - defaults
dependencies:
    - python>=3.8
    - astroid
    - boltons>=20.1
    - bottleneck>=1.3.1
    - cf_xarray>=0.6.1
    - cftime>=1.4.1
    - Click >=8.1
    - dask>=2.6.0
    - jsonpickle
    - lmoments3
    - numba
    - numpy>=1.16
    - pandas>=0.23,<2.0 # Pinned due to incompatibility with xarray <=2023.03
    - pint>=0.9
    - poppler>=0.67
    - pyyaml
    - scikit-learn>=0.21.3
    - scipy>=1.2
    - xarray>=2022.06.0
    # Extras
    - clisops
    - eofs
    - flox
    - pytest-json-report  # Added due to a packaging bug with ESMPy. See: https://github.com/esmf-org/esmf/issues/115
  # Testing and development dependencies
    - black>=22.12
    - blackdoc
    - bump2version
    - cairosvg
    - coverage
    - distributed>=2.0
    - flake8
    - flake8-rst-docstrings
    - flit
    - h5netcdf
    - ipykernel
    - ipython
    - matplotlib
    - mypy
    - nbsphinx
    - nbval
    - nc-time-axis
    - netCDF4>=1.4
    - pooch
    - pre-commit
    - pybtex
    - pydocstyle
    - pylint<2.15
    - pytest
    - pytest-cov
    - pytest-xdist>=3.2
    - sphinx
    - sphinx-autodoc-typehints
    - sphinx-codeautolink
    - sphinx-copybutton
    - sphinx-rtd-theme>=1.0
    - sphinxcontrib-bibtex
    - statsmodels
    - tokenize-rt
    - tox
#    - tox-conda  # Will be added when a tox@v4.0+ compatible plugin is released.
    - xdoctest
    - yamale
    - yamllint
    - pip
    - pip:
        - flake8-alphabetize
        - sphinxcontrib-svg2pdfconverter
