name: Bump Patch Version

on:
  push:
    branches:
      - master
    paths-ignore:
      - .*
      - .github/**.yml
      - CHANGES.rst
      - Makefile
      - docs/**.ipynb
      - docs/**.py
      - docs/**.rst
      - docs/Makefile
      - docs/make.bat
      - docs/references.bib
      - environment.yml
      - pylintrc
      - pyproject.toml
      - requirements_dev.txt
      - requirements_upstream.txt
      - setup.cfg
      - tox.ini
      - xclim/__init__.py

jobs:
  bump_patch_version:
    name: Bumpversion Patch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          persist-credentials: false
      - uses: actions/setup-python@v4.7.1
        with:
          python-version: "3.x"
      - name: Config Commit Bot
        run: |
          git config --local user.email "bumpversion[bot]@ouranos.ca"
          git config --local user.name "bumpversion[bot]"
      - name: Current Version
        run: |
          CURRENT_VERSION="$(grep -E '__version__'  xclim/__init__.py | cut -d ' ' -f3)"
          echo "current_version=${CURRENT_VERSION}"
      - name: Bump Patch Version
        run: |
          python -m pip install bump2version
          echo "running `bump2version patch`"
          NEW_VERSION="$(grep -E '__version__'  xclim/__init__.py | cut -d ' ' -f3)"
          echo "new_version=${NEW_VERSION}"
      - name: Push Changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          force: false
          github_token: ${{ secrets.BUMPVERSION_TOKEN }}
          branch: ${{ github.ref }}
