# Dependency Review Action
#
# This Action will scan dependency manifest files that change as part of a Pull Request, surfacing known-vulnerable versions of the packages declared or updated in the PR. Once installed, if the workflow run is marked as required, PRs introducing known-vulnerable packages will be blocked from merging.
#
# Source repository: https://github.com/actions/dependency-review-action
# Public documentation: https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement
name: Dependency Review
on:
  pull_request:

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: "ubuntu-latest"
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          disable-sudo: true
          egress-policy: audit
          # egress-policy: block
          # allowed-endpoints: >
          #   api.deps.dev:443
          #   api.electricitymap.org:443
          #   api.github.com:443
          #   api.green-coding.io:443
          #   api.securityscorecards.dev:443
          #   github.com:443
          #   ip-api.com:80
          #   ipapi.co:443
          #   proxy.golang.org:443
          #   pypi.org:443
          #   sum.golang.org:443

      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@0fd2200a8f02d7939066c535e3642c2ebee9db16 # v5.2
        with:
          task: start-measurement
          branch: ${{ github.head_ref || github.ref_name }}
          project: "xclim"
          machine: "ubuntu-latest"
          tags: "CI/CD, Main"
          gmt-api-token: WRONGVALUES1234567890

      - name: Checkout Repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Dependency Review
        uses: actions/dependency-review-action@3c4e3dcb1aa7874d2c16be7d79418e9b7efd6261 # v4.8.2

      - name: Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@0fd2200a8f02d7939066c535e3642c2ebee9db16 # v5.2
        with:
          task: get-measurement
          label: 'Dependency Review'
        continue-on-error: true

      - name: Show Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@0fd2200a8f02d7939066c535e3642c2ebee9db16 # v5.2
        with:
          task: display-results
        continue-on-error: true
